---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: docker
    commands:
      - docker build -t rg.nl-ams.scw.cloud/silvergh0st/rss2tlgrm:${DRONE_COMMIT_BRANCH} .
      - docker push rg.nl-ams.scw.cloud/silvergh0st/rss2tlgrm:${DRONE_COMMIT_BRANCH}
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker

volumes:
  - name: cache
    host:
      path: /opt/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: cloud.lyalyuev.info
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd /opt
        - docker-compose pull rss2tlgrm
        - docker-compose up -d --remove-orphans rss2tlgrm

trigger:
  branch:
    - master

depends_on:
  - build
