---
kind: pipeline
type: docker
name: build-latest

steps:
  - name: build
    image: docker
    commands:
      - docker build -t dntskdev/rss2tlgrm:latest .
      - docker push dntskdev/rss2tlgrm:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker

volumes:
  - name: cache
    host:
      path: /opt/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: build-tag

steps:
  - name: build
    image: docker
    commands:
      - docker build -t dntskdev/rss2tlgrm:$DRONE_TAG .
      - docker tag dntskdev/rss2tlgrm:$DRONE_TAG dntskdev/rss2tlgrm:latest
      - docker push dntskdev/rss2tlgrm:$DRONE_TAG dntskdev/rss2tlgrm:latest
    volumes:
      - name: cache
        path: /root/.cache/pip
      - name: docker_sock
        path: /var/run/docker.sock
      - name: docker_config
        path: /root/.docker

volumes:
  - name: cache
    host:
      path: /opt/docker/drone/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: docker_config
    host:
      path: /root/.docker

trigger:
  event:
    - tag
