# Generated by Django 3.0.9 on 2020-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('feed', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('last_item', models.URLField(blank=True, null=True)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
    ]
