# Generated by Django 3.0.9 on 2020-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss2tlgrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
