# Generated by Django 3.0.9 on 2020-08-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss2tlgrm', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='last_item',
        ),
    ]
